-- CRIANDO BANCO DE DADOS DE E-COMMERCE
CREATE DATABASE ECOMMERCE;
USE ECOMMERCE;

-- CRIANDO TABELA - CLIENTES
CREATE TABLE CLIENTES (
    IDCLIENTE INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NOMECLIENTE VARCHAR(100) NOT NULL,
    CEPENDERECO CHAR(8) NOT NULL,
    NUMEROENDERECO CHAR(3) NOT NULL,
    ISPESSOAFISICA BOOL NOT NULL,
    CPF CHAR(11) UNIQUE,
    CNPJ CHAR(14) UNIQUE,
    CONSTRAINT CHK_CPF_CNPJ CHECK (
        (ISPESSOAFISICA = TRUE AND CPF IS NOT NULL AND CNPJ IS NULL) OR
        (ISPESSOAFISICA = FALSE AND CNPJ IS NOT NULL AND CPF IS NULL)
    )
);

-- CRIANDO TABELA - PRODUTO
CREATE TABLE PRODUTO (
    IDPRODUTO INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NOMEPRODUTO VARCHAR(50) NOT NULL,
    PRECO FLOAT NOT NULL,
    CATEGORIA ENUM('ELETRÔNICOS', 'BRINQUEDOS', 'ROUPAS', 'ALIMENTOS', 'MÓVEIS') NOT NULL DEFAULT 'ELETRÔNICOS',
    DESCRICAOPRODUTO VARCHAR(100) NOT NULL
);

-- CRIANDO TABELA - PEDIDO
CREATE TABLE PEDIDO (
    IDPEDIDO INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    IDCLIENTE INT NOT NULL,
    STATUSPEDIDO ENUM('CANCELADO', 'EM PROGRESSO', 'PROCESSANDO', 'ENVIADO', 'ENTREGUE') NOT NULL DEFAULT 'EM PROGRESSO',
    DESCRICAOPEDIDO VARCHAR(100) NOT NULL,
    PRECOENVIO FLOAT NOT NULL,
    CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTES(IDCLIENTE)
);

-- CRIANDO TABELA - PEDIDO_TEM_PRODUTOS
CREATE TABLE PEDIDO_TEM_PRODUTOS (
    IDPEDIDO INT,
    IDPRODUTO INT,
    QUANTIDADE INT NOT NULL,
    PRIMARY KEY (IDPEDIDO, IDPRODUTO),
    CONSTRAINT FK_PTP_PEDIDO FOREIGN KEY (IDPEDIDO) REFERENCES PEDIDO(IDPEDIDO),
    CONSTRAINT FK_PTP_PRODUTO FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO(IDPRODUTO)
);

-- CRIANDO TABELA - ESTOQUE
CREATE TABLE ESTOQUE (
    IDESTOQUE INT AUTO_INCREMENT PRIMARY KEY,
    LOCALESTOQUE VARCHAR(45) NOT NULL
);

-- CRIANDO TABELA - FORNECEDOR
CREATE TABLE FORNECEDOR (
    IDFORNECEDOR INT AUTO_INCREMENT PRIMARY KEY,
    NOMEFANTASIA VARCHAR(50) NOT NULL,
    CNPJ CHAR(14) NOT NULL,
    INFOCONTATO CHAR(11) NOT NULL,
    CONSTRAINT UN_FORNECEDOR UNIQUE(CNPJ)
);

-- CRIANDO TABELA - TERCEIROS (OUTROS VENDEDORES)
CREATE TABLE TERCEIRO (
    IDTERCEIRO INT AUTO_INCREMENT PRIMARY KEY,
    LOCALIZACAO VARCHAR(45) NOT NULL,
    NOMECOMERCIAL VARCHAR(45) NOT NULL,
    RAZAOSOCIAL VARCHAR(45) NOT NULL,
    CNPJ CHAR(14) NOT NULL,
    CONSTRAINT UN_TERCEIRO UNIQUE (NOMECOMERCIAL, CNPJ)
);

-- CRIANDO TABELA - EM_ESTOQUE
CREATE TABLE EM_ESTOQUE (
    IDPRODUTO INT,
    IDESTOQUE INT,
    QUANTIDADE INT NOT NULL,
    PRIMARY KEY (IDPRODUTO, IDESTOQUE),
    CONSTRAINT FK_EE_PRODUTO FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO(IDPRODUTO),
    CONSTRAINT FK_EE_ESTOQUE FOREIGN KEY (IDESTOQUE) REFERENCES ESTOQUE(IDESTOQUE)
);

-- CRIANDO TABELA - FORNECEDOR_TEM_PRODUTOS
CREATE TABLE FORNECEDOR_TEM_PRODUTOS (
    IDFORNECEDOR INT,
    IDPRODUTO INT,
    QUANTIDADE INT NOT NULL,
    PRIMARY KEY (IDFORNECEDOR, IDPRODUTO),
    CONSTRAINT FK_FTP_FORNECEDOR FOREIGN KEY (IDFORNECEDOR) REFERENCES FORNECEDOR(IDFORNECEDOR),
    CONSTRAINT FK_FTP_PRODUTO FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO(IDPRODUTO)
);

-- CRIANDO TABELA - TERCEIRO_TEM_PRODUTOS
CREATE TABLE TERCEIRO_TEM_PRODUTOS (
    IDTERCEIRO INT,
    IDPRODUTO INT,
    QUANTIDADE INT NOT NULL,
    PRIMARY KEY (IDTERCEIRO, IDPRODUTO),
    CONSTRAINT FK_TTP_TERCEIRO FOREIGN KEY (IDTERCEIRO) REFERENCES TERCEIRO(IDTERCEIRO),
    CONSTRAINT FK_TTP_PRODUTO FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO(IDPRODUTO)
);

-- CRIANDO TABELA - CARTAO
CREATE TABLE CARTAO (
    IDCARTAO INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    IDCLIENTE INT NOT NULL,
    NUMEROCARTAO CHAR(16) NOT NULL UNIQUE,
    DATAVALIDADE DATE NOT NULL,
    CVV INT NOT NULL,
    CONSTRAINT FK_CARTAO_CLIENTE FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTES(IDCLIENTE)
);

-- CRIANDO TABELA - ENTREGA
CREATE TABLE ENTREGA (
    IDENTREGA INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    IDPEDIDO INT NOT NULL,
    STATUSENTREGA ENUM('EM TRANSPORTE', 'ENTREGUE', 'CANCELADA') DEFAULT 'EM TRANSPORTE' NOT NULL,
    CODIGORASTREAMENTO CHAR(16) NOT NULL UNIQUE,
    CONSTRAINT FK_ENTREGA_PEDIDO FOREIGN KEY (IDPEDIDO) REFERENCES PEDIDO(IDPEDIDO)
);

-- CRIANDO TABELA - PIX
CREATE TABLE PIX (
    IDPIX INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    IDPEDIDO INT NOT NULL,
    CODIGOPIX VARCHAR(77) NOT NULL,
    CONSTRAINT FK_PIX_PEDIDO FOREIGN KEY (IDPEDIDO) REFERENCES PEDIDO(IDPEDIDO)
);
